all - hc release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -120,8 +120,17 @@ jobs:
 
           anchor build
           cp -r ./target/deploy/*.so .
-          cargo release publish \
-            --workspace --execute --no-confirm
+
+          PACKAGES=("aligned-sized" "light-heap" "light-utils" "light-bounded-vec" "light-hasher" "light-macros" "light-hash-set" "light-merkle-tree-reference" "light-concurrent-merkle-tree" "light-indexed-merkle-tree" "light-circuitlib-rs" "light-verifier" "account-compression" "light-registry" "light-system-program" "light-compressed-token" "light-test-utils")
+          for PACKAGE in "${PACKAGES[@]}"; do
+            for attempt in {1..3}; do
+              echo "Attempt $attempt: Publishing $PACKAGE..."
+              cargo release publish --package "$PACKAGE" --execute --no-confirm && break || echo "Attempt $attempt failed, retrying in 60..."
+              sleep 60
+            done
+            echo "Sleeping for 60 seconds to handle rate limits..."
+            sleep 60
+          done
 
       - name: Release Rust project
         if: steps.extract-project.outputs.package != 'all' && steps.extract-project.outputs.language == 'rust'
@@ -140,8 +149,7 @@ jobs:
           cp -r ./target/deploy/*.so .
 
           cargo release publish \
-            --package "$PACKAGE" \
-            --token "$CARGO_REGISTRY_TOKEN"
+            --package "$PACKAGE"
 
       - name: Release TypeScript
         if: steps.extract-project.outputs.package != 'all' && steps.extract-project.outputs.language == 'ts'
